# Generated by Django 5.0.5 on 2024-05-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
