# Generated by Django 5.0.5 on 2024-05-08 14:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('authorName', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('authorEmail', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
