# Generated by Django 4.2.13 on 2024-09-04 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
