# Generated by Django 5.0.5 on 2024-05-08 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_authorname_project_promoter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='authorEmail',
        ),
    ]
