# Generated by Django 5.0.5 on 2024-05-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_project_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('selected', 'Selecionado'), ('declined', 'Recusado')], default='pending', max_length=8),
        ),
    ]
