# Generated by Django 5.0.5 on 2024-05-11 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_project_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['status', '-created_at'], 'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
    ]
