# Generated by Django 4.2.13 on 2024-06-03 12:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0001_initial'),
        ('city', '0002_alter_city_options'),
        ('project', '0014_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='city.city'),
        ),
        migrations.AddField(
            model_name='project',
            name='community',
            field=models.TextField(default='Jarjar', validators=[django.core.validators.MaxLengthValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='neighborhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='neighborhood.neighborhood'),
        ),
    ]
