# Generated by Django 4.2.13 on 2024-06-03 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0017_projectvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectvote',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_staff': True, 'is_superuser': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='projectvote',
            unique_together={('project', 'user')},
        ),
    ]
