# Generated by Django 4.2.13 on 2024-06-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_alter_projectvote_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='file',
            field=models.FileField(blank=True, upload_to='document/files/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.FileField(blank=True, upload_to='document/images/'),
        ),
    ]
