# Generated by Django 5.0.5 on 2024-05-11 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Município', 'verbose_name_plural': 'Municípios'},
        ),
    ]
