# Generated by Django 5.0.5 on 2024-05-11 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['full_name'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
