# Generated by Django 4.2.13 on 2024-06-03 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='community',
            field=models.TextField(default='Jarjar', validators=[django.core.validators.MaxLengthValidator(100)]),
            preserve_default=False,
        ),
    ]
